### ISSUE TITLE
Provide a non CardView-based Adapter

### ISSUE THREAD

**Issue by DreierF** [oriley-me/homage#13] opened 2016-05-20 13:59 UTC
Hey,

It's me again. I would like to have an (expandable-)adapter that does not wrap every library into a CardView and therefore follow the Material Design Guidelines:
<img width="622" alt="bildschirmfoto 2016-05-20 um 15 53 30" src="https://cloud.githubusercontent.com/assets/5631865/15429963/7c276958-1ea3-11e6-94e2-c55e83866e61.png">
Source: [Material Design Guidelines](https://www.google.com/design/spec/components/cards.html#cards-usage)

**Comment by kaneoriley** [comment] 2016-05-20 16:04
Hey,

That seems like a simple enough request, although I'll need to think about it. You could easily copy the expandable card view and make it extend something else (like FrameLayout) if you wanted to for yourself, but I'm not sure how best to do it in Homage. I don't want to make the base view require nesting since that will just lower performance, so I might need to extract some logic out to make it easier to have different base view types. Either that, or see if it's possible to programmatically remove the card background so I can add a constructor parameter and don't need to add any extra classes/methods to achieve this, as one of my main goals is keeping the method count as low as possible.

**Comment by kaneoriley** [comment] 2016-06-02 00:40
I had another look and I don't think this applies, as it only specifically says not to use cards for content that 'doesn't have many actions'. The cards in homage have at least 2, which by the look of the docs is the magic number that says it should probably be on a card.

**Comment by DreierF** [comment] 2016-06-02 07:44
Ok, I still disagree. They suggest to use cards when there are **more** than two actions. Homage has the link and an expand button as far as I know. Furthermore cards should be used to present content of different types or length, where the card helps to visually separate each item. But since Homage displays the same type of content in every item, I think the cards are more distracting. 
But if you are still not convinced, you can close the issue and I will just adjust the implementation for my app accordingly ;-)

**Comment by kaneoriley** [comment] 2016-06-02 07:50
That's fair enough, it's a grey area at best. I'm happy to accept a pull request, but I just have other priorities at the moment. It's quite easy to setup your own adapter if you don't like the included one, which is by design. I want to keep Homage lightweight and low method count so it doesnt become another dependency I want to remove from my apps.

**Comment by DreierF** [comment] 2016-06-02 07:53
Great :)
I'll submit a pull request when I'm done ;-)

**Comment by kaneoriley** [comment] 2016-06-08 23:53
Merged, sorry it took a bit longer than I'd hoped.

**Closed as completed by kaneoriley** 2016-06-08 23:53 UTC
